services:
  backend:
    image: audio-ecommerce-backend
    container_name: audio-api
    ports:
      - '${PORT_API}:8080'
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - JAVA_TOOL_OPTIONS=-Djava.net.preferIPv4Stack=true
