spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

app:
  security:
    cookie-name: auth_token
    cookie-secure: ${COOKIE_SECURE:false}
    same-site: ${COOKIE_SAMESITE:Lax}

api:
  security:
    token:
      secret: ${JWT_SECRET:bananas-for-secret-key}
