spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  mail:
    host: ${SPRING_MAIL_HOST:smtp.mailtrap.io}
    port: ${SPRING_MAIL_PORT:2525}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

app:
  email:
    from: ${APP_EMAIL_FROM:demomailtrap.co}
  url:
    frontend: ${FRONTEND_URL:https://audio-app-ecommerce.vercel.app}
    backend: ${BACKEND_URL:https://audio-ecommerce.onrender.com/}
  security:
    cookie-secure: ${COOKIE_SECURE:true}
    same-site: ${COOKIE_SAMESITE:None}
  security:
    cookie-secure: true
    same-site: None
