spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

api:
  security:
    token:
      secret: ${JWT_SECRET}

---
# Perfil de DESENVOLVIMENTO (Local)
spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

app:
  email:
    from: ${APP_EMAIL_FROM:no-reply@audioapp.com}
  url:
    frontend: http://localhost:5173
    backend: http://localhost:8080
  security:
    cookie-name: auth_token
    cookie-secure: false
    same-site: Lax

---
# Perfil de PRODUÇÃO (Render)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

app:
  email:
    from: ${APP_EMAIL_FROM}
  url:
    frontend: ${FRONTEND_URL:https://audio-app-ecommerce.vercel.app}
    backend: ${BACKEND_URL:https://audio-ecommerce.onrender.com/}
  security:
    cookie-name: auth_token
    cookie-secure: true
    same-site: None
